### ISSUE TITLE
Logging System - Core

### ISSUE THREAD

**Issue by jkeon** [decline-cookies/anvil-csharp-core#33]
A logging system for Anvil that can be used across the different assemblies with different output depending on the context. 

Can be phased quite nicely so this issue can be split into separate issues.

### PHASE 1

- [x] Standard API for logging from a global context similar to `Console.WriteLine` or `Debug.Log`.
- [x] When in the C# Assembly - redirect ultimate output to `Console.xxx` or whatever is appropriate.
- [x] When in the Unity (even if the code resides in the C# assembly) - redirect ultimate output to `Debug.xxx` or whatever is appropriate.

This will solve the current issue with the `ConsoleRedirect` and `UnityConsoleTextWriter` where EVERYTHING that is piped through `Console.WriteLine` shows up in the Unity Console. Ideally we only want things that are from our code/framework. Today we get that but also all of Unity's internals. 

### PHASE 2 to X

Bunch of ideas for discussion at this point.

- Support for categorization with sub-categorization.  (#46)
   - Ability to turn on/off different categories. (Logging CAN be expensive, would be great to conditional the functions so they can be wiped from the build when a category is off)
   - Colors for categories.
   - Maybe a way to see the log in the app? 
- [x] Ability to dump the log to a file?
- ~~Ability to email the log somewhere? Thinking about future Customer Support applications but maybe that's App specific built on top of this.~~
- [ ] Encryption support. Logs are written using a public key to encrypt them so end users can't read them but the info is there and safe. They email to customer support and CS has the private key to decrypt and see what's going on?
- Look at LogCat and take what is good.

**Comment by mbaker3** [comment]
Updated the original issue comments to TODO lists.
Will stub out issues for the incomplete functionality to deal with some other day.
